---

- name: "configuration play." 
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  tasks: 
    - name: "Shell"
      shell: |
        echo "hello $TYPEORM_CONNECTION $TYPEORM_PORT"

  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'MY_VAR')}}"
    - TYPEORM_PORT: 5432
